refactor: Replace Status with BTStatus
ThePat02/BehaviourToolkit pull request #41
Opened 2023-11-24 10:58 UTC by ThePat02

Replaced Status with BTStatus. This was done by search and replace and needs to be tested!

2023-11-24 13:48 UTC, ThePat02 commented
> Blackboard to BTBlackboard

No, since this can be used with FSM too, so maybe `BehaviourBlackboard`

2023-11-24 15:21 UTC, SirPigeonz commented
Lol I though BT stands for Behavior Toolkit haha maybe we should think about our own prefix for all classes to avoid collusions like `Bt` ?

2023-11-24 15:25 UTC, SirPigeonz commented
GDScript needs namespaces...

2023-11-24 16:43 UTC, SirPigeonz commented
> I think just `Behaviour` should do.

Yeah it's fine.

> I really want to keep things like `FiniteStateMachine` without any additional Pre or suffixes.

Yeah it's a paint in ass. I'm just concerned if use would want to use other addon with conflicting name (it's generic name it's high chance for it). GDScript needs namespaces for addons lol xD

2023-11-24 16:45 UTC, SirPigeonz requested changes

2023-11-24 16:51 UTC, ThePat02 commented on addons/behaviour_toolkit/behaviour_tree/bt_root.gd
> +var current_BTStatus: BTBehaviour.BTStatus
> While doing refactoring like that I recommend to use the refactoring tool as a jump-to tool and approve each change manually. :)

Yes! I just tried replacing all of it for the ease of things before diving deeper into the code.

2023-11-27 11:39 UTC, ThePat02 commented on addons/behaviour_toolkit/behaviour_tree/leaves/leaf_event.gd
Same with `return_BTStatus`

2023-11-27 11:40 UTC, ThePat02 commented on addons/behaviour_toolkit/finite_state_machine/fsm.gd
Same issue

2023-11-27 11:40 UTC, ThePat02 commented on addons/behaviour_toolkit/finite_state_machine/fsm_state_integrated_bt.gd
Same Issue

2023-11-27 11:52 UTC, ThePat02 commented
Needs testing, as I fixed this in codespaces.

2023-11-27 14:25 UTC, SirPigeonz commented
I've checked the code and looks good! At least what it's worth, my atention span today is of a golden retriever xD

Will take this PR on test ride today night :)

2023-11-28 18:18 UTC, SirPigeonz commented on addons/behaviour_toolkit/behaviour_tree/composites/bt_integrated_fsm.gd
>  		state_machine.active = false
Should be `current_bt_status` not `current_status` :)
```suggestion
	if not state_machine.current_bt_status == BTStatus.RUNNING:
```

2023-11-28 18:18 UTC, SirPigeonz commented on addons/behaviour_toolkit/behaviour_tree/composites/bt_integrated_fsm.gd
```suggestion
	return state_machine.current_bt_status
```

2023-11-28 18:34 UTC, SirPigeonz commented
Ok tested it above bug is the only one I found.
After that one fix I think it's fine to merge. :)

2023-11-28 18:38 UTC, ThePat02 commented
> Ok tested it and above bug is the only one I found.
After that one fix I think it's fine to merge. :)

If something else is broken pls open another issue. Cant test it right now as I am working in codespaces!

2023-11-28 18:38 UTC, merged